dicks/dicks/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from .views import *

urlpatterns = [
    path('reader/', include('reader.urls')),
    path('approver/', include('approver.urls')),
    path('', include('django.contrib.auth.urls')),
    path('update/', include('editclient.urls')),
    path('enroller/', include('enroller.urls')),
    path('batchupload/', include('batchupload.urls')),
    path('admin/', admin.site.urls),
    # path('503/', Test503.as_view())
]

dicks/reader/forms.py
from django import forms
from django.utils import dateformat, formats


class ReportGenerateForm(forms.Form):
    
    from_date = forms.DateField(
        # input_formats = ['%Y/%m/%d'],
        widget = forms.DateInput(
            attrs = {
                'class': 'form-control',
                'type': 'date'
            }
        )
    )
    to_date = forms.DateField(
        # input_formats = ['%d/%m/%Y'],
        widget = forms.DateInput(
            attrs = {
                'class': 'form-control',
                'type': 'date'
            }
        )
    )
    
    
    
class OverallReportGenerateForm(forms.Form):
    CHOICES =(
        ('OVERALL','Overall Sales'),
        ('PREMIUM','By Premium Paid'),
        ('HO-ARD','HO/ARD')
    )
    report_format = forms.ChoiceField(
        choices = CHOICES,
        widget = forms.Select(
            attrs = {
                'class': 'form-control',
                'type':'button'
            }
        )
    )
    from_date = forms.DateField(
        # input_formats = ['%Y/%m/%d'],
        widget = forms.DateInput(
            attrs = {
                'class': 'form-control',
                'type': 'date'
            }
        )
    )
    to_date = forms.DateField(
        # input_formats = ['%d/%m/%Y'],
        widget = forms.DateInput(
            attrs = {
                'class': 'form-control',
                'type': 'date'
            }
        )
    )

dicks/frontend/templates/503.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        {% block css %}
        <!--Custom styles for this template-->
        <link
          rel="icon"
          href="{% static 'ampc-logo-high-res.png' %}"
          height="100"
          width="100"
        />
        <link rel="stylesheet" href="{% static 'custom_css/error-pages.css' %}">
        {% endblock %}
        <title>AGDAO COOP | Page not found</title>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 custom-text">
                    
                    <h1><i class="fas fa-exclamation-triangle fa-lg fa-fw"></i>Oh no, you've found our junior developer's homepage!</h1>
                    <h4>Despite sleeping on the couch most of the day, our junior web developer still finds time to do some coding...</h3>
                    <br></br>
                    <code>ERROR 503 Service Unavailable</code>
                </div>
                <div class="custom-footer">
                    {% include 'footer.html' %}
                </div>
            </div>
        </div>
    </body>
</html>

dicks/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        {% load static %}
        <meta charset="utf-8">
        {% block pagetitle %}{% endblock pagetitle %}
        <meta name="viewport" content="width=device-width, shrink-to-fit=no initial-scale=1.0">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link rel="stylesheet" type="text/css" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'custom_css/base.css' %}">
        <link rel="icon" href="{% static 'ampc-logo-high-res.png' %}">
        
        <!-- Bootstrap 4 -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

        <!-- Font Awesome -->
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        <!-- Moment.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

        <!-- Tempus Dominus Bootstrap 4 -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
        
        {% block css %}{% endblock css %}
    </head>
    <body>
        {% include "page-header.html" %}
        <div class="container">
            <div class="row">
                <div class="messages-only text-center">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}
                    
                </div>
            </div>
        </div>
        {% block content %}{% endblock content %}
    </body>
</html>

dicks/frontend/templates/footer.html
{% load static %}
{% block css %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'custom_css/login.css' %}">
{% endblock css %}
<footer class="footer py-3">
    <div class="container">
        <div class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-muted">© 2021 Agdao Multipurpose Cooperative <span class="app-version"></span>
            </p>
        
            <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
              <img src="http://agdaocoop.com/wp-content/uploads/2020/02/ampc-logo-Artboard-1@3x.png" alt="site-logo" height="40vw">
            </a>
        
            <ul class="nav col-md-4 justify-content-end">
              <li class="nav-item"><a href="https://agdaocoop.com" class="nav-link px-2 text-muted">Site</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Privacy</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            </ul>
        </div>
    </div>
</footer>

dicks/frontend/templates/page-header.html
{% load static %}
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        {# <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg> #}
        <img src="{% static 'ampc-logo-high-res.png' %}" height="40vw" alt="" class="bi me-2">
    </a>
    <div class="text-center d-none d-print-block">
        <h3 class="h3">Agdao Multipurpose Cooperative</h3>
        <p>{{ request.user.agent.branch }} Branch</p>
    </div>
    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 d-print-none">
        {% if user.agent.designation.designation_name == "Branch Manager" %}
            <li> <a href="{% url 'pay-approver-home' %}" class="nav-link px-2 link-dark">Home</a> </li>
            <li>
                <a class="nav-link px-2 link-dark" id="paymentsdropdown1" data-bs-toggle="dropdown" aria-expanded="false">
                Payments <i class="far fa-caret-square-down fa-sm"></i>
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="paymentsdropdown1">
                    <li> <a href="{% url 'reader-approved' %}"class="dropdown-item">Approved</a> </li>
                    <li> <a href="{% url 'reader-cancelled' %}"class="dropdown-item">Cancelled</a> </li>
                </ul>
            </li>
            <li><a href="{% url 'reports-home' %}" class="nav-link px-2 link-dark">Reports</a></li>
        {% elif user.agent.designation.designation_name == "IT Admin" or user.agent.designation.designation_name == "HO-Marketing Staff" %}
            <li> <a href="{% url 'pay-approver-home' %}" class="nav-link px-2 link-dark">Home</a> </li>
            <li>
                <a class="nav-link px-2 link-dark" id="paymentsdropdown1" data-bs-toggle="dropdown" aria-expanded="false">
                Payments <i class="far fa-caret-square-down fa-sm"></i>
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="paymentsdropdown1">
                    <li> <a href="{% url 'reader-approved' %}"class="dropdown-item">Approved</a> </li>
                    <li> <a href="{% url 'reader-cancelled' %}"class="dropdown-item">Cancelled</a> </li>
                </ul>
            </li>
            <li>
                <a href="{% url 'overall-home' %}" class="nav-link px-2 link-dark">
                    Reports 
                </a>
            </li>
        {% else %}
            <li> <a href="{% url 'marketing-home' %}" class="nav-link px-2 link-dark">Home</a> </li>
            <li><a href="{% url 'encode' %}" class="nav-link px-2 link-dark">New</a></li>
            <li> <a class="nav-link px-2 link-dark" id="paymentsdropdown2" data-bs-toggle="dropdown" aria-expanded="false">
                Payments <i class="far fa-caret-square-down fa-sm"></i>
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="paymentsdropdown2">
                    <li> <a href="{% url 'reader-pendings' %}" class="dropdown-item">Pending</a> </li>
                    <li> <a href="{% url 'reader-approved' %}"class="dropdown-item">Approved</a> </li>
                    <li> <a href="{% url 'reader-cancelled' %}"class="dropdown-item">Cancelled</a> </li>
                </ul>
            </li>
        {% endif %}
        <li><a href="{% url 'logout' %}" class="nav-link px-2 btn btn-outline-danger btn-sm logout-button link-dark">Log Out</a></li>
    </ul>

    <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 d-print-none" action="{% url 'search' %}">
        <input type="text" class="form-control" name="searchtext" placeholder="Search..." aria-label="Search">
    </form>

    <div class="text-end">
        <a href="#" class="d-block link-dark text-decoration-none" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <p class="nav-link px-2 mt-2 link-dark d-print-none">
                {% if user.agent %}
                    {{ user.agent.designation }}
                    <br>
                    {{ user.agent.branch }}
                {% else %}
                    Not Logged In
                {% endif %}
            </p>
        </a>
        {# <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1"> #}
            {# <li><a class="dropdown-item" href="#">New project...</a></li> #}
            {# <li><a class="dropdown-item" href="#">Settings</a></li> #}
            {# <li><a class="dropdown-item" href="#">Profile</a></li> #}
            {# <li><hr class="dropdown-divider"></li> #}
            {# <li><a class="dropdown-item" href="#">Sign out</a></li> #}
        {# </ul> #}
        
    </div>
</div>

dicks/frontend/templates/scratch_pad.html
<td>payor</td>
<td>encoder_branch</td>
<td>membership_branch</td>
<td>{{items.date_of_payment}}</td>
<td>{{items.recording_date}}</td>
<td>{{items.update_date}}</td>
<td>{{items.cutoff_period}}</td>
<td>{{items.premium_paid}}</td>
<td>{{items.auth_agent}}</td>
<td>{{items.payment_type}}</td>
<td>{{items.tagging}}</td>
<td>{{items.beneficiary1}}</td>
<td>{{items.beneficiary2}}</td>

{% for labels in label_list  %}
    <tr>
        <th>{{ labels }}</th>
    {# </tr> #}
{% endfor %}
{% for items in info_list %}
    {# <tr> #}
        <td>{{ items.update_date }}</td>
    </tr>
{% endfor %}

{# PaymentDetails #}
payor
encoder_branch
membership_branch
date_of_payment
recording_date
update_date
cutoff_period
premium_paid
auth_agent
payment_type
tagging
beneficiary1
beneficiary2

{# dropdown menu #}
<ul class="dropdown-menu text-small" aria-labelledby="paymentsdropdown">
    <li> <a class="dropdown-item">Pending</a> </li>
    <li> <a class="dropdown-item">Approved</a> </li>
    <li> <a class="dropdown-item">Cancelled</a> </li>
</ul>

{# bg image 503/404 #}
http://agdaocoop.com/wp-content/uploads/2021/10/altumcode-P2SkP_PXhlU-unsplash.jpg
Photo by <a href="https://unsplash.com/@altumcode?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">AltumCode</a> on <a href="https://unsplash.com/s/photos/coffee-and-code?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>

{# icon #}
<link
  rel="icon"
  href="{% static 'ampc-logo-high-res.png' %}"
  height="100"
  width="100"
/>

{# center a row class #}
{# used in reports menu #}
position-absolute top-50 start-50 translate-middle

{# own-sales-home #}
<form class="form-action" action="/reader/generate-report/request/preview/" method="post">
    {% csrf_token %}
    <table class="table">
        <tbody>
            <tr>
                <td>
                    <label for="from_date">From:</label>
                </td>
                <td>
                    <div class="input-group date" id="datepicker1" data-target-input="nearest">
                        <input type="text" name="from_date" class=" form-control datetimepicker-input" data-target="datepicker1" required="" id="id_from_date" value="{{ from_date }}">
                        <div class="input-group-append" data-target="#datepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <label for="to_date">To:</label>
                </td>
                <td>
                    <div class="input-group date" id='datepicker2' data-target-input="nearest">
                        <input type="text" name="to_date" class=" form-control datetimepicker-input" data-target="datepicker2" required="" id="id_from_date" value="{{ to_date }}">
                        <div class="input-group-append" data-target='#datepicker2' data-toggle='datetimepicker'>
                            <div class="input-group-text">
                                <i class="fa fa-calendar"></i>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="text-center">
                    <button type="submit" name="button" class="btn btn-primary btn-sm generate-button">Generate</button>
                </td>
            </tr>
        </tbody>
    </table>
</form>